name: todark
description: Task management application

publish_to: "none"

version: 1.5.1+41

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.0.16
  shared_preferences: ^2.2.3 
  firebase_core: ^3.0.0
  firebase_core_platform_interface: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  path: ^1.9.0
  intl: ^0.19.0
  iconsax: ^0.0.8
  timezone: ^0.9.3
  workmanager: ^0.5.2
  home_widget: ^0.6.0
  file_picker: ^8.0.3
  restart_app: ^1.2.1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  time_machine: ^0.9.17
  bottom_picker: ^2.7.0
  dynamic_color: ^1.7.0
  path_provider: ^2.1.3
  table_calendar: ^3.1.1
  flutter_timezone: ^1.0.8
  package_info_plus: ^8.0.0
  flex_color_picker: ^3.5.0
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/google_fonts/

dependency_overrides:
  _fe_analyzer_shared: ^70.0.0
  analyzer: ^6.4.1
  build_runner_core: ^7.3.1
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  test_api: ^0.7.2
  vm_service: ^14.2.3
