// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdiKkiDzczpbJAwy2dw4Kb9GPUaO1epu8',
    appId: '1:106503309304:web:a52e3df384d4602df1780d',
    messagingSenderId: '106503309304',
    projectId: 'onedo-e1fe8',
    authDomain: 'onedo-e1fe8.firebaseapp.com',
    storageBucket: 'onedo-e1fe8.appspot.com',
    measurementId: 'G-ZR8BGP5CXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADlM6qbLXVpMEiSv-TKwm2jjl-6QMf7ck',
    appId: '1:106503309304:android:117b48f47b8e4031f1780d',
    messagingSenderId: '106503309304',
    projectId: 'onedo-e1fe8',
    storageBucket: 'onedo-e1fe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYUp1auwudrO6UC_WURN4Zcu9b42cRQpY',
    appId: '1:106503309304:ios:6d3d4ba54df895a8f1780d',
    messagingSenderId: '106503309304',
    projectId: 'onedo-e1fe8',
    storageBucket: 'onedo-e1fe8.appspot.com',
    iosBundleId: 'com.yoshi.todark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYUp1auwudrO6UC_WURN4Zcu9b42cRQpY',
    appId: '1:106503309304:ios:7e55eaa66ee74a7cf1780d',
    messagingSenderId: '106503309304',
    projectId: 'onedo-e1fe8',
    storageBucket: 'onedo-e1fe8.appspot.com',
    iosBundleId: 'com.example.darkTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdiKkiDzczpbJAwy2dw4Kb9GPUaO1epu8',
    appId: '1:106503309304:web:3c9d63f17031de54f1780d',
    messagingSenderId: '106503309304',
    projectId: 'onedo-e1fe8',
    authDomain: 'onedo-e1fe8.firebaseapp.com',
    storageBucket: 'onedo-e1fe8.appspot.com',
    measurementId: 'G-S76H5FF2R0',
  );
}
